### ISSUE TITLE
Why is MN is showing yellow with current block count?

### ISSUE THREAD

**Issue by presman** [XinFinOrg/XinFin-Node#13]
Hello Support Team - I have a test MN running with a name "XinFin-MN-PS".  All weekend, the name would show as yellow while it maintained a current block count and numbers updating.

Can you see from your side what the problem might be?  From my view, it looks as if everything is correct and it was running green last week.  I can not see any problems from the xdc.log file.

My test Mn is running but I do not know if it processing properly on your side.  If it is not, could you please provide some guidance on where the problem is?

Thank you again for all of your help.

Preston

**Comment by shrikantgoswami** [comment]
Hello @presman, it seems that your node is working perfectly fine, there are a few health checks that a node has to pass through that determine it's color. 

I have identified it's because of the number of peers that your node is able to discover (2) this should be more than (3). 

We would fixing this & it should automatically turn green.

Regards
